user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
    
_user_secured:
    resource: "@UserBundle/Controller/SecuredController.php"
    type:     annotation
    
user_order:
    path:     /order
    defaults: { _controller: UserBundle:Order:index }