<?php

namespace SM\Bundle\UserBundle\Repository;

use SM\Bundle\UserBundle\Repository\BaseRepository;
use SM\Bundle\UserBundle\Constants\Configs;
use Doctrine\ORM\Query;

/**
 * ThucDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThucDonRepository extends BaseRepository
{
    public function getListMenu()
    {
        $result = $this->createQueryBuilder('td')
        ->select('td.idThucDon, td.name')
        ->getQuery();
        $arrReturn = $this->customListAllThucDon($result->getArrayResult());

        return $arrReturn;
    }
    private function customListAllThucDon($listThucDon = array())
    {
        $arrReturn = array();
        foreach ($listThucDon as $arrThucDon) {
            $arrReturn[$arrThucDon['idThucDon']] = $arrThucDon['name'];
        }
        return $arrReturn;
    }
	public function getThucDonByCategory($idCategory = 1)
	{
		$result = $this->createQueryBuilder('td')
		->select('td')
		->where('td.idCategory = :idCategory')
		->setParameter('idCategory', $idCategory)
		->getQuery();
		return $result->getArrayResult();
	}
	public function getThucDonByCategoryInArray($idCategory = 1, $listid = array())
	{
		$result = $this->createQueryBuilder('td')
		->select('td, CuaHangThucDon')
		->leftJoin('td.idThucDon','CuaHangThucDon')
		->where('td.idCategory = :idCategory')
		->setParameter('idCategory', $idCategory)
		->andWhere('td.idThucDon IN (:listid)')
		->setParameter('listid', $listid)
		->getQuery();
		return $result->getArrayResult();
	}
}