<?php

namespace SM\Bundle\UserBundle\Repository;

use SM\Bundle\UserBundle\Repository\BaseRepository;
use SM\Bundle\UserBundle\Constants\Configs;
use Doctrine\ORM\Query;

/**
 * ThucDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThucDonRepository extends BaseRepository
{
	public function getThucDonByCategory($idCategory = 1)
	{
		$result = $this->createQueryBuilder('td')
		->select('td')
		->where('td.idCategory = :idCategory')
		->setParameter('idCategory', $idCategory)
		->getQuery();
		return $result->getArrayResult();
	}
}