admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    
_admin_secured:
    resource: "@AdminBundle/Controller/SecuredController.php"
    type:     annotation

admin_cuahang:
    path:     /cuahang
    defaults: { _controller: AdminBundle:CuaHang:index }
    
admin_cuahang_create:
    path:     /cuahang/create
    defaults: { _controller: AdminBundle:CuaHang:create }
    
admin_cuahang_detail:
    path:     /cuahang/detail/{id}
    defaults: { _controller: "AdminBundle:CuaHang:detail", id: 1 }
    
admin_thucdon:
    path:     /thucdon
    defaults: { _controller: AdminBundle:ThucDon:index }