admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    
_admin_secured:
    resource: "@AdminBundle/Controller/SecuredController.php"
    type:     annotation

admin_cuahang:
    path:     /cuahang
    defaults: { _controller: AdminBundle:CuaHang:index }
    
admin_cuahang_create:
    path:     /cuahang/create
    defaults: { _controller: AdminBundle:CuaHang:create }
    
admin_cuahang_edit:
    path:     /cuahang/edit/{id}
    defaults: { _controller: "AdminBundle:CuaHang:edit", id: 1 }
    
admin_cuahang_delete:
    path:     /cuahang/delete/{id}
    defaults: { _controller: "AdminBundle:CuaHang:delete", id: -1 }
    
admin_cuahang_detail:
    path:     /cuahang/detail/{id}
    defaults: { _controller: "AdminBundle:CuaHang:detail", id: 1 }
    
admin_cuahang_detail_delete:
    path:     /cuahang/detail/delete/{idCuaHangThucDon}/{idCuaHang}
    defaults: { _controller: "AdminBundle:CuaHang:detailDelete", idCuaHangThucDon: -1, idCuahang: -1 }
    
admin_thucdon:
    path:     /thucdon
    defaults: { _controller: AdminBundle:ThucDon:index }
    
admin_thucdon_create:
    path:     /thucdon/create
    defaults: { _controller: AdminBundle:ThucDon:create }
    
admin_thucdon_edit:
    path:     /thucdon/edit/{id}
    defaults: { _controller: "AdminBundle:ThucDon:edit", id: 1 }
    
admin_thucdon_delete:
    path:     /thucdon/delete/{id}
    defaults: { _controller: "AdminBundle:ThucDon:delete", id: -1 }