admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
